// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_shortener_id_ from "./routes/api/shortener/[id].tsx";
import * as $api_shortener_index from "./routes/api/shortener/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $s_id_ from "./routes/s/[id].tsx";
import * as $tools_shortener_id_ from "./routes/tools/shortener/[id].tsx";
import * as $tools_shortener_index from "./routes/tools/shortener/index.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/shortener/[id].tsx": $api_shortener_id_,
    "./routes/api/shortener/index.tsx": $api_shortener_index,
    "./routes/index.tsx": $index,
    "./routes/s/[id].tsx": $s_id_,
    "./routes/tools/shortener/[id].tsx": $tools_shortener_id_,
    "./routes/tools/shortener/index.tsx": $tools_shortener_index,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
